//
// Created by dev on 8/28/22.
//

#ifndef COURSE_RENDERER_CONST_H
#define COURSE_RENDERER_CONST_H

const int MAX_PIXELS_PER_KERNEL = 5000;

const int VIRTUAL_GEOMETRY_VERTICES = 10000;
const int VIRTUAL_GEOMETRY_FACES = 100000;

#endif//COURSE_RENDERER_CONST_H
